name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

      # Restore all of our .NET Core Local Tools
      - name: .NET Core Local Tool Restore
        run: dotnet tool restore --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

      # Verify that the code is formatted correctly
      - name: dotnet-format
        run: dotnet format --fix-style warn --fix-analyzers warn --check

      # Build the Solution
      - name: Build Solution
        run: dotnet build -graphBuild -maxCpuCount --configuration Release

      # Upload Artifacts
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
            name: ManipulativeReplacer-${{ github.sha }}
            path: |
              ManipulativeReplacer/bin/Release/ManipulativeReplacer.exe
              ManipulativeReplacer/bin/Release/ManipulativeReplacer.exe.config
              ManipulativeReplacer/bin/Release/ManipulativeReplacer.pdb
