# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: ManipulativeReplacer.sln

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

        # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild

        # Build the Solution
      - name: Build Solution
        run: msbuild $env:Solution_Name /m /graph /restore /t:Build /p:Configuration=Release /p:RestoreUsingStaticGraphEvaluation=true

